version: '4.19'

services:
  db:
    image: postgres
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_DB: exercicioCampeonato
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
    ports:
    - "5432:5432"
    volumes:
      - postgres:/data/campeonato

volumes:
  postgres: